# Generated by Django 2.2.2 on 2019-07-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodEvento', models.IntegerField()),
                ('NomeEvento', models.CharField(max_length=255)),
                ('NomeConvenio', models.CharField(max_length=255)),
                ('Categoria', models.CharField(max_length=40)),
                ('Situacao', models.CharField(max_length=40)),
                ('DataInicio', models.DateTimeField()),
                ('DataFim', models.DateTimeField()),
                ('NumeroVagas', models.IntegerField()),
                ('NomeEventoInformacao', models.CharField(max_length=255)),
                ('DescricaoEventoInformacao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
