# Generated by Django 2.2.2 on 2019-07-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=700)),
            ],
            options={
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
