# Generated by Django 2.2.2 on 2019-07-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='registro',
            new_name='registros',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='token',
        ),
    ]
